__default__:
    system: 'slurm' #check if system is defined below
    account: mbrockley #required
    time: 990 # minutes
    mem: 4 # GB
    mem_cpu: 3000
    threads: 8
    queue: standard # required
    nodes: 1
    command_options:
        slurm:
            command: "sbatch --parsable --qos=unlim"
            key_mapping:
            name: "--job-name={}"
            threads: "-n {}"
            mem: "--mem={}g"
            mem_cpu: "--mem-per-cpu={}GB"
            account: "--account={}"
            queue: "--partition={}"
            time: "--time={}"
            nodes: "-N {}"      # ntasks: 24
convert:
    name: seqtk
    queue: standard
    threads: 20
    mem: 4
    mem_cpu: 3000
    time: 360

prodigal:
    name: protein conversion
    queue: standard
    threads: 20
    mem: 3
    mem_cpu: 3000
    time: 360

parse:
    name: index sequences
    queue: himem-standard 
    mem: 200
    time: 720

hmmbuild: 
    name: HMMbuild
    queue: standard
    threads: 1
    mem: 1
    time: 120

hmmsearch: 
    name: HMMER search
    queue: standard
    threads: 8
    mem: 4
    time: 120

eval_filter:
    name: list generator
    queue: standard
    mem: 3
    time: 30

easel_profile:
    name: ssi generator
    queue: standard
    mem: 6
    time: 120

easel_fetch:
    name: threshold fetcher
    queue: standard
    mem: 4
    time: 480
